#

# DO NOT EDIT THIS FILE - THIS DOCUMENTATION WAS CREATED BY A SCRIPT - see EJAM/data-raw/datacreate_ejscreen_acs_tables.R or similar files

#' @name ejscreen_acs_tables
#' @docType data
#' @title tables needed for EJSCREEN ACS-based indicators as of EJSCREEN version 2.32 released 2024 and also for EJAM version 2.32.003 released 11/2025
'ejscreen_acs_tables'
